// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using raBudget.Infrastructure.Database;

namespace raBudget.Api.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20201229133924_BuudgetBalance2")]
    partial class BuudgetBalance2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetId");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetBalance", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetId");

                    b.ToTable("BudgetBalances");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryIconId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BudgetCategoryType")
                        .HasColumnType("int");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("BudgetCategoryId");

                    b.HasIndex("BudgetCategoryIconId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory+BudgetedAmount", b =>
                {
                    b.Property<Guid>("BudgetedAmountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetedAmountId");

                    b.HasIndex("BudgetCategoryId");

                    b.ToTable("BudgetedAmount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategoryIcon", b =>
                {
                    b.Property<Guid>("BudgetCategoryIconId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IconKey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BudgetCategoryIconId");

                    b.ToTable("BudgetCategoryIcons");

                    b.HasData(
                        new
                        {
                            BudgetCategoryIconId = new Guid("fd663b2c-5681-49d0-8a64-002730b3db81"),
                            IconKey = "mdi-car"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("103d4df7-ad2d-4f1a-bc74-c071e3122d6b"),
                            IconKey = "mdi-cart"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("4dde2768-2002-4d83-bd8d-338297dbd944"),
                            IconKey = "mdi-train-car"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("455a7555-9d7a-4942-b356-cf9310fdc3a0"),
                            IconKey = "mdi-wallet-travel"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("72aed05e-a0de-42ae-9648-82c621a2b480"),
                            IconKey = "mdi-wrench"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("5e7557ca-508d-410d-9337-b5142a1aa9b3"),
                            IconKey = "mdi-basket"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b8d279fd-8cbf-4ee4-91e0-e7f3b37e02c0"),
                            IconKey = "mdi-gamepad"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("352073ec-ec62-4bad-b6a1-0765613f5cf2"),
                            IconKey = "mdi-phone"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("3bd660b1-da2f-4a02-8314-f5e9b9db744c"),
                            IconKey = "mdi-airplane"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("10036d5e-b5f7-4b07-a003-1e253ba1284a"),
                            IconKey = "mdi-currency-usd-circle-outline"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("d4ba9894-3340-40e9-bd51-c66ed205f2cb"),
                            IconKey = "mdi-format-paint"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("8f685fe6-256d-49f5-85cb-b6f654ec1dff"),
                            IconKey = "mdi-gamepad-square"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("3b386577-b735-4865-b8b6-4ceba240cb06"),
                            IconKey = "mdi-laptop"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("ca6ef496-6b7b-4efd-9ea6-31260e5cdbb3"),
                            IconKey = "mdi-camera"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("12fdffbd-174c-496d-885e-945998c76483"),
                            IconKey = "mdi-city"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b40b5c91-b5b7-4dee-8094-053d55b5ba06"),
                            IconKey = "mdi-fire"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("bc56fd81-9b1a-44ee-ac58-83f00630e0b2"),
                            IconKey = "mdi-dumbbell"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9adb902a-055b-4e22-8865-baf11a520fde"),
                            IconKey = "mdi-coffee"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("3f903a15-ad29-419d-8d66-8edab0093f0a"),
                            IconKey = "mdi-dice-5"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("fffce917-53a0-4b34-b541-fe0cf4147fbf"),
                            IconKey = "mdi-beach"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("ee3ce367-f5b1-420b-96e0-639e2963e120"),
                            IconKey = "mdi-bus-articulated-front"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("7bba5790-0d79-4e72-afa8-de83df360d7a"),
                            IconKey = "mdi-smoking"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("6490022e-3e3c-4e1b-b56b-a7c2852b5732"),
                            IconKey = "mdi-fridge"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("43b17e01-a739-49fe-ba18-a1ac2a5177d0"),
                            IconKey = "mdi-baby-face"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("801f3f62-5800-4717-8c2c-2d0f1ad70f80"),
                            IconKey = "mdi-paw"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("978b4ecb-7aa0-44a3-b132-bd663c749ff0"),
                            IconKey = "mdi-bandage"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("43b1237f-fcb2-41e6-8d9c-654d4a70a9ec"),
                            IconKey = "mdi-human"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9254cd52-6459-4617-a24b-a5c40bded3b5"),
                            IconKey = "mdi-sofa"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("73b81678-f1a1-4918-9237-6c5dc771027c"),
                            IconKey = "mdi-memory"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("a1d77525-d3f2-4390-869a-690e06ccf5ec"),
                            IconKey = "mdi-cellphone-android"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("e649888b-b567-4604-bc18-634ed36e929c"),
                            IconKey = "mdi-speaker"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9d9bc6ed-fd32-49a6-ad21-3730b3dc1480"),
                            IconKey = "mdi-sim"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("60099806-dfda-4f0e-8d84-95994cb5cace"),
                            IconKey = "mdi-silverware-fork-knife"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("efaa40dc-b468-49b3-8923-e24740720b9d"),
                            IconKey = "mdi-food"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("d9ce1a30-79e9-4c49-a08f-6fb6ab0515be"),
                            IconKey = "mdi-gas-station"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("7ae437a8-ab10-4593-8d85-7eda3fcea083"),
                            IconKey = "mdi-hospital-building"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("e8aeb56a-d14c-47c8-90a5-7fd658695ca6"),
                            IconKey = "mdi-shopping"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("70d6ca9e-b85e-45af-8f7f-5c10a6439518"),
                            IconKey = "mdi-glass-cocktail"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("5e59e08e-b1d3-44bb-8c20-7afb9c223cc9"),
                            IconKey = "mdi-filmstrip"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("fec64dcb-5504-4486-8b2d-fb3077532d4e"),
                            IconKey = "mdi-bike"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("018872e6-2030-4854-b7a4-3ccaab83f19f"),
                            IconKey = "mdi-motorbike"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("ef3575f3-0687-4f81-bfb0-4528f0499b6d"),
                            IconKey = "mdi-wallet-giftcard"
                        });
                });

            modelBuilder.Entity("raBudget.Domain.Entities.SubTransaction", b =>
                {
                    b.Property<Guid>("SubTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("char(36)");

                    b.HasKey("SubTransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SubTransaction");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("raBudget.Domain.Models.Currency", b =>
                {
                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EnglishName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NativeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CurrencyCode");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyCode = 8,
                            Code = "ALL",
                            EnglishName = "Albanian Lek",
                            NativeName = "Leku shqiptar",
                            Symbol = "Lekë"
                        },
                        new
                        {
                            CurrencyCode = 12,
                            Code = "DZD",
                            EnglishName = "Algerian Dinar",
                            NativeName = "دينار جزائري",
                            Symbol = "د.ج.‏"
                        },
                        new
                        {
                            CurrencyCode = 32,
                            Code = "ARS",
                            EnglishName = "Argentine Peso",
                            NativeName = "peso argentino",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 36,
                            Code = "AUD",
                            EnglishName = "Australian Dollar",
                            NativeName = "Australian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 48,
                            Code = "BHD",
                            EnglishName = "Bahraini Dinar",
                            NativeName = "دينار بحريني",
                            Symbol = "د.ب.‏"
                        },
                        new
                        {
                            CurrencyCode = 50,
                            Code = "BDT",
                            EnglishName = "Bangladeshi Taka",
                            NativeName = "বাংলাদেশী টাকা",
                            Symbol = "৳"
                        },
                        new
                        {
                            CurrencyCode = 51,
                            Code = "AMD",
                            EnglishName = "Armenian Dram",
                            NativeName = "հայկական դրամ",
                            Symbol = "֏"
                        },
                        new
                        {
                            CurrencyCode = 68,
                            Code = "BOB",
                            EnglishName = "Bolivian Boliviano",
                            NativeName = "boliviano",
                            Symbol = "Bs"
                        },
                        new
                        {
                            CurrencyCode = 84,
                            Code = "BZD",
                            EnglishName = "Belize Dollar",
                            NativeName = "Belize Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 96,
                            Code = "BND",
                            EnglishName = "Brunei Dollar",
                            NativeName = "Dolar Brunei",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 116,
                            Code = "KHR",
                            EnglishName = "Cambodian Riel",
                            NativeName = "រៀល​កម្ពុជា",
                            Symbol = "៛"
                        },
                        new
                        {
                            CurrencyCode = 124,
                            Code = "CAD",
                            EnglishName = "Canadian Dollar",
                            NativeName = "Canadian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 144,
                            Code = "LKR",
                            EnglishName = "Sri Lankan Rupee",
                            NativeName = "ශ්‍රී ලංකා රුපියල",
                            Symbol = "රු."
                        },
                        new
                        {
                            CurrencyCode = 152,
                            Code = "CLP",
                            EnglishName = "Chilean Peso",
                            NativeName = "CLP",
                            Symbol = "CLP"
                        },
                        new
                        {
                            CurrencyCode = 156,
                            Code = "CNY",
                            EnglishName = "Chinese Yuan",
                            NativeName = "ཡུ་ཨན་",
                            Symbol = "¥"
                        },
                        new
                        {
                            CurrencyCode = 170,
                            Code = "COP",
                            EnglishName = "Colombian Peso",
                            NativeName = "peso colombiano",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 188,
                            Code = "CRC",
                            EnglishName = "Costa Rican Colón",
                            NativeName = "colón costarricense",
                            Symbol = "₡"
                        },
                        new
                        {
                            CurrencyCode = 191,
                            Code = "HRK",
                            EnglishName = "Croatian Kuna",
                            NativeName = "hrvatska kuna",
                            Symbol = "HRK"
                        },
                        new
                        {
                            CurrencyCode = 203,
                            Code = "CZK",
                            EnglishName = "Czech Koruna",
                            NativeName = "česká koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            CurrencyCode = 208,
                            Code = "DKK",
                            EnglishName = "Danish Krone",
                            NativeName = "dansk krone",
                            Symbol = "kr."
                        },
                        new
                        {
                            CurrencyCode = 214,
                            Code = "DOP",
                            EnglishName = "Dominican Peso",
                            NativeName = "peso dominicano",
                            Symbol = "RD$"
                        },
                        new
                        {
                            CurrencyCode = 230,
                            Code = "ETB",
                            EnglishName = "Ethiopian Birr",
                            NativeName = "ETB",
                            Symbol = "Br"
                        },
                        new
                        {
                            CurrencyCode = 320,
                            Code = "GTQ",
                            EnglishName = "Guatemalan Quetzal",
                            NativeName = "quetzal",
                            Symbol = "Q"
                        },
                        new
                        {
                            CurrencyCode = 340,
                            Code = "HNL",
                            EnglishName = "Honduran Lempira",
                            NativeName = "lempira hondureño",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = 344,
                            Code = "HKD",
                            EnglishName = "Hong Kong Dollar",
                            NativeName = "Hong Kong Dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            CurrencyCode = 348,
                            Code = "HUF",
                            EnglishName = "Hungarian Forint",
                            NativeName = "magyar forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            CurrencyCode = 352,
                            Code = "ISK",
                            EnglishName = "Icelandic Króna",
                            NativeName = "íslensk króna",
                            Symbol = "ISK"
                        },
                        new
                        {
                            CurrencyCode = 356,
                            Code = "INR",
                            EnglishName = "Indian Rupee",
                            NativeName = "ভাৰতীয় ৰুপী",
                            Symbol = "₹"
                        },
                        new
                        {
                            CurrencyCode = 360,
                            Code = "IDR",
                            EnglishName = "Indonesian Rupiah",
                            NativeName = "Rupiah Indonesia",
                            Symbol = "Rp"
                        },
                        new
                        {
                            CurrencyCode = 364,
                            Code = "IRR",
                            EnglishName = "Iranian Rial",
                            NativeName = "ریال ایران",
                            Symbol = "ریال"
                        },
                        new
                        {
                            CurrencyCode = 368,
                            Code = "IQD",
                            EnglishName = "Iraqi Dinar",
                            NativeName = "دينار عراقي",
                            Symbol = "د.ع.‏"
                        },
                        new
                        {
                            CurrencyCode = 376,
                            Code = "ILS",
                            EnglishName = "Israeli New Shekel",
                            NativeName = "שקל חדש",
                            Symbol = "₪"
                        },
                        new
                        {
                            CurrencyCode = 388,
                            Code = "JMD",
                            EnglishName = "Jamaican Dollar",
                            NativeName = "Jamaican Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 392,
                            Code = "JPY",
                            EnglishName = "Japanese Yen",
                            NativeName = "日本円",
                            Symbol = "￥"
                        },
                        new
                        {
                            CurrencyCode = 398,
                            Code = "KZT",
                            EnglishName = "Kazakhstani Tenge",
                            NativeName = "Қазақстан теңгесі",
                            Symbol = "₸"
                        },
                        new
                        {
                            CurrencyCode = 400,
                            Code = "JOD",
                            EnglishName = "Jordanian Dinar",
                            NativeName = "دينار أردني",
                            Symbol = "د.أ.‏"
                        },
                        new
                        {
                            CurrencyCode = 404,
                            Code = "KES",
                            EnglishName = "Kenyan Shilling",
                            NativeName = "Shilingi ya Kenya",
                            Symbol = "Ksh"
                        },
                        new
                        {
                            CurrencyCode = 410,
                            Code = "KRW",
                            EnglishName = "South Korean Won",
                            NativeName = "대한민국 원",
                            Symbol = "₩"
                        },
                        new
                        {
                            CurrencyCode = 414,
                            Code = "KWD",
                            EnglishName = "Kuwaiti Dinar",
                            NativeName = "دينار كويتي",
                            Symbol = "د.ك.‏"
                        },
                        new
                        {
                            CurrencyCode = 417,
                            Code = "KGS",
                            EnglishName = "Kyrgystani Som",
                            NativeName = "Кыргызстан сому",
                            Symbol = "сом"
                        },
                        new
                        {
                            CurrencyCode = 418,
                            Code = "LAK",
                            EnglishName = "Laotian Kip",
                            NativeName = "ລາວ ກີບ",
                            Symbol = "₭"
                        },
                        new
                        {
                            CurrencyCode = 422,
                            Code = "LBP",
                            EnglishName = "Lebanese Pound",
                            NativeName = "جنيه لبناني",
                            Symbol = "ل.ل.‏"
                        },
                        new
                        {
                            CurrencyCode = 434,
                            Code = "LYD",
                            EnglishName = "Libyan Dinar",
                            NativeName = "دينار ليبي",
                            Symbol = "د.ل.‏"
                        },
                        new
                        {
                            CurrencyCode = 446,
                            Code = "MOP",
                            EnglishName = "Macanese Pataca",
                            NativeName = "澳門元",
                            Symbol = "MOP$"
                        },
                        new
                        {
                            CurrencyCode = 458,
                            Code = "MYR",
                            EnglishName = "Malaysian Ringgit",
                            NativeName = "Malaysian Ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            CurrencyCode = 462,
                            Code = "MVR",
                            EnglishName = "Maldivian Rufiyaa",
                            NativeName = "MVR",
                            Symbol = "ރ."
                        },
                        new
                        {
                            CurrencyCode = 484,
                            Code = "MXN",
                            EnglishName = "Mexican Peso",
                            NativeName = "peso mexicano",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 496,
                            Code = "MNT",
                            EnglishName = "Mongolian Tugrik",
                            NativeName = "төгрөг",
                            Symbol = "₮"
                        },
                        new
                        {
                            CurrencyCode = 504,
                            Code = "MAD",
                            EnglishName = "Moroccan Dirham",
                            NativeName = "درهم مغربي",
                            Symbol = "د.م.‏"
                        },
                        new
                        {
                            CurrencyCode = 512,
                            Code = "OMR",
                            EnglishName = "Omani Rial",
                            NativeName = "ريال عماني",
                            Symbol = "ر.ع.‏"
                        },
                        new
                        {
                            CurrencyCode = 524,
                            Code = "NPR",
                            EnglishName = "Nepalese Rupee",
                            NativeName = "नेपाली रूपैयाँ",
                            Symbol = "नेरू"
                        },
                        new
                        {
                            CurrencyCode = 554,
                            Code = "NZD",
                            EnglishName = "New Zealand Dollar",
                            NativeName = "New Zealand Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 558,
                            Code = "NIO",
                            EnglishName = "Nicaraguan Córdoba",
                            NativeName = "córdoba nicaragüense",
                            Symbol = "C$"
                        },
                        new
                        {
                            CurrencyCode = 578,
                            Code = "NOK",
                            EnglishName = "Norwegian Krone",
                            NativeName = "norske kroner",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = 586,
                            Code = "PKR",
                            EnglishName = "Pakistani Rupee",
                            NativeName = "روپئیہ",
                            Symbol = "ر"
                        },
                        new
                        {
                            CurrencyCode = 590,
                            Code = "PAB",
                            EnglishName = "Panamanian Balboa",
                            NativeName = "balboa panameño",
                            Symbol = "B/."
                        },
                        new
                        {
                            CurrencyCode = 600,
                            Code = "PYG",
                            EnglishName = "Paraguayan Guarani",
                            NativeName = "guaraní paraguayo",
                            Symbol = "Gs."
                        },
                        new
                        {
                            CurrencyCode = 604,
                            Code = "PEN",
                            EnglishName = "Peruvian Sol",
                            NativeName = "sol peruano",
                            Symbol = "S/"
                        },
                        new
                        {
                            CurrencyCode = 608,
                            Code = "PHP",
                            EnglishName = "Philippine Piso",
                            NativeName = "Philippine Piso",
                            Symbol = "₱"
                        },
                        new
                        {
                            CurrencyCode = 634,
                            Code = "QAR",
                            EnglishName = "Qatari Rial",
                            NativeName = "ريال قطري",
                            Symbol = "ر.ق.‏"
                        },
                        new
                        {
                            CurrencyCode = 643,
                            Code = "RUB",
                            EnglishName = "Russian Ruble",
                            NativeName = "RUB",
                            Symbol = "RUB"
                        },
                        new
                        {
                            CurrencyCode = 646,
                            Code = "RWF",
                            EnglishName = "Rwandan Franc",
                            NativeName = "RWF",
                            Symbol = "RF"
                        },
                        new
                        {
                            CurrencyCode = 682,
                            Code = "SAR",
                            EnglishName = "Saudi Riyal",
                            NativeName = "ريال سعودي",
                            Symbol = "ر.س.‏"
                        },
                        new
                        {
                            CurrencyCode = 702,
                            Code = "SGD",
                            EnglishName = "Singapore Dollar",
                            NativeName = "Singapore Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 704,
                            Code = "VND",
                            EnglishName = "Vietnamese Dong",
                            NativeName = "Đồng Việt Nam",
                            Symbol = "₫"
                        },
                        new
                        {
                            CurrencyCode = 710,
                            Code = "ZAR",
                            EnglishName = "South African Rand",
                            NativeName = "Suid-Afrikaanse rand",
                            Symbol = "R"
                        },
                        new
                        {
                            CurrencyCode = 752,
                            Code = "SEK",
                            EnglishName = "Swedish Krona",
                            NativeName = "ruoŧŧa kruvdno",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = 756,
                            Code = "CHF",
                            EnglishName = "Swiss Franc",
                            NativeName = "Schweizer Franken",
                            Symbol = "CHF"
                        },
                        new
                        {
                            CurrencyCode = 760,
                            Code = "SYP",
                            EnglishName = "Syrian Pound",
                            NativeName = "ليرة سورية",
                            Symbol = "ل.س.‏"
                        },
                        new
                        {
                            CurrencyCode = 764,
                            Code = "THB",
                            EnglishName = "Thai Baht",
                            NativeName = "บาท",
                            Symbol = "฿"
                        },
                        new
                        {
                            CurrencyCode = 780,
                            Code = "TTD",
                            EnglishName = "Trinidad & Tobago Dollar",
                            NativeName = "Trinidad & Tobago Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 784,
                            Code = "AED",
                            EnglishName = "United Arab Emirates Dirham",
                            NativeName = "درهم إماراتي",
                            Symbol = "د.إ.‏"
                        },
                        new
                        {
                            CurrencyCode = 788,
                            Code = "TND",
                            EnglishName = "Tunisian Dinar",
                            NativeName = "دينار تونسي",
                            Symbol = "د.ت.‏"
                        },
                        new
                        {
                            CurrencyCode = 807,
                            Code = "MKD",
                            EnglishName = "Macedonian Denar",
                            NativeName = "Македонски денар",
                            Symbol = "ден"
                        },
                        new
                        {
                            CurrencyCode = 818,
                            Code = "EGP",
                            EnglishName = "Egyptian Pound",
                            NativeName = "جنيه مصري",
                            Symbol = "ج.م.‏"
                        },
                        new
                        {
                            CurrencyCode = 826,
                            Code = "GBP",
                            EnglishName = "British Pound",
                            NativeName = "Punt Prydain",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = 840,
                            Code = "USD",
                            EnglishName = "US Dollar",
                            NativeName = "US ᎠᏕᎳ",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 858,
                            Code = "UYU",
                            EnglishName = "Uruguayan Peso",
                            NativeName = "peso uruguayo",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 860,
                            Code = "UZS",
                            EnglishName = "Uzbekistani Som",
                            NativeName = "Ўзбекистон сўм",
                            Symbol = "сўм"
                        },
                        new
                        {
                            CurrencyCode = 886,
                            Code = "YER",
                            EnglishName = "Yemeni Rial",
                            NativeName = "ريال يمني",
                            Symbol = "ر.ي.‏"
                        },
                        new
                        {
                            CurrencyCode = 901,
                            Code = "TWD",
                            EnglishName = "New Taiwan Dollar",
                            NativeName = "新台幣",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 941,
                            Code = "RSD",
                            EnglishName = "Serbian Dinar",
                            NativeName = "Српски динар",
                            Symbol = "RSD"
                        },
                        new
                        {
                            CurrencyCode = 944,
                            Code = "AZN",
                            EnglishName = "Azerbaijani Manat",
                            NativeName = "AZN",
                            Symbol = "₼"
                        },
                        new
                        {
                            CurrencyCode = 946,
                            Code = "RON",
                            EnglishName = "Romanian Leu",
                            NativeName = "leu românesc",
                            Symbol = "RON"
                        },
                        new
                        {
                            CurrencyCode = 949,
                            Code = "TRY",
                            EnglishName = "Turkish Lira",
                            NativeName = "Türk Lirası",
                            Symbol = "₺"
                        },
                        new
                        {
                            CurrencyCode = 952,
                            Code = "XOF",
                            EnglishName = "West African CFA Franc",
                            NativeName = "Mbuuɗu Seefaa BCEAO",
                            Symbol = "CFA"
                        },
                        new
                        {
                            CurrencyCode = 971,
                            Code = "AFN",
                            EnglishName = "Afghan Afghani",
                            NativeName = "افغانی افغانستان",
                            Symbol = "؋"
                        },
                        new
                        {
                            CurrencyCode = 972,
                            Code = "TJS",
                            EnglishName = "Tajikistani Somoni",
                            NativeName = "Сомонӣ",
                            Symbol = "сом."
                        },
                        new
                        {
                            CurrencyCode = 975,
                            Code = "BGN",
                            EnglishName = "Bulgarian Lev",
                            NativeName = "Български лев",
                            Symbol = "лв."
                        },
                        new
                        {
                            CurrencyCode = 977,
                            Code = "BAM",
                            EnglishName = "Bosnia-Herzegovina Convertible Mark",
                            NativeName = "Конвертибилна марка",
                            Symbol = "КМ"
                        },
                        new
                        {
                            CurrencyCode = 978,
                            Code = "EUR",
                            EnglishName = "Euro",
                            NativeName = "euro",
                            Symbol = "€"
                        },
                        new
                        {
                            CurrencyCode = 980,
                            Code = "UAH",
                            EnglishName = "Ukrainian Hryvnia",
                            NativeName = "українська гривня",
                            Symbol = "₴"
                        },
                        new
                        {
                            CurrencyCode = 981,
                            Code = "GEL",
                            EnglishName = "Georgian Lari",
                            NativeName = "ქართული ლარი",
                            Symbol = "₾"
                        },
                        new
                        {
                            CurrencyCode = 985,
                            Code = "PLN",
                            EnglishName = "Polish Zloty",
                            NativeName = "złoty polski",
                            Symbol = "zł"
                        },
                        new
                        {
                            CurrencyCode = 986,
                            Code = "BRL",
                            EnglishName = "Brazilian Real",
                            NativeName = "Real brasileiro",
                            Symbol = "R$"
                        });
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.HasOne("raBudget.Domain.Models.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetBalance", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "IncomeTotal", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "SavingTotal", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "SpendingTotal", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "TotalBalance", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "UnassignedFunds", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.Navigation("IncomeTotal");

                    b.Navigation("SavingTotal");

                    b.Navigation("SpendingTotal");

                    b.Navigation("TotalBalance");

                    b.Navigation("UnassignedFunds");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.BudgetCategoryIcon", "BudgetCategoryIcon")
                        .WithMany()
                        .HasForeignKey("BudgetCategoryIconId");

                    b.HasOne("raBudget.Domain.Entities.Budget", null)
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId");

                    b.Navigation("BudgetCategoryIcon");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory+BudgetedAmount", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.BudgetCategory", null)
                        .WithMany("BudgetedAmounts")
                        .HasForeignKey("BudgetCategoryId");

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BudgetedAmountId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetedAmountId");

                            b1.ToTable("BudgetedAmount");

                            b1.WithOwner()
                                .HasForeignKey("BudgetedAmountId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.SubTransaction", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.Transaction", null)
                        .WithMany("SubTransactions")
                        .HasForeignKey("TransactionId");

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("SubTransactionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("SubTransactionId");

                            b1.ToTable("SubTransaction");

                            b1.WithOwner()
                                .HasForeignKey("SubTransactionId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.Navigation("BudgetCategories");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("BudgetedAmounts");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("SubTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
