// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using raBudget.Infrastructure.Database;

namespace raBudget.Api.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetId");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryIconId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BudgetCategoryType")
                        .HasColumnType("int");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("BudgetCategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory+BudgetedAmount", b =>
                {
                    b.Property<Guid>("BudgetedAmountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetedAmountId");

                    b.HasIndex("BudgetCategoryId");

                    b.ToTable("BudgetedAmount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategoryIcon", b =>
                {
                    b.Property<Guid>("BudgetCategoryIconId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IconKey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BudgetCategoryIconId");

                    b.ToTable("BudgetCategoryIcons");

                    b.HasData(
                        new
                        {
                            BudgetCategoryIconId = new Guid("c4b9bb46-e5bb-41ee-84c2-bf3fb4c406e9"),
                            IconKey = "mdi-car"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("6b8623c7-c719-4888-9ca5-4b57b63ab658"),
                            IconKey = "mdi-cart"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("a5d13a05-3fd2-4311-ab10-812fbf594c9a"),
                            IconKey = "mdi-train-car"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("48a0d93d-a6f4-4424-becf-fc23329a2a6a"),
                            IconKey = "mdi-wallet-travel"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("82c812ac-81e8-4af6-ad07-f06c9f21c7bd"),
                            IconKey = "mdi-wrench"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("25abbc59-132e-4eb7-92ca-de876069a867"),
                            IconKey = "mdi-basket"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("d32cdebe-75bd-427f-96a2-40a5cab8d893"),
                            IconKey = "mdi-gamepad"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b480dd2c-e0e0-4d67-8e9d-a596162445c6"),
                            IconKey = "mdi-phone"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("1a84fe5c-c60a-4007-bfc7-fc4113283aa0"),
                            IconKey = "mdi-airplane"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("ab3fd2cd-dd91-40e9-81c7-e5ba29d9e410"),
                            IconKey = "mdi-currency-usd-circle-outline"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("f2d7effc-3c7a-4cc9-baa8-a28546bc3482"),
                            IconKey = "mdi-format-paint"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("8e49667b-6eda-415e-b7d5-65fae76a2d56"),
                            IconKey = "mdi-gamepad-square"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("91709684-a325-4acc-ad0d-715212bc28f4"),
                            IconKey = "mdi-laptop"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("f565696c-d7c1-4173-90ad-1c971e00af95"),
                            IconKey = "mdi-camera"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9f4067c4-ea7d-4feb-94b3-d0eaabcf53de"),
                            IconKey = "mdi-city"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("66678e2a-6667-44b5-a5d3-4d306d5f1074"),
                            IconKey = "mdi-fire"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("83b0391d-78fa-46f3-a17f-4df666b65338"),
                            IconKey = "mdi-dumbbell"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("a4d70c56-66ac-404c-b137-7d0f71b47b1b"),
                            IconKey = "mdi-coffee"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("80b46725-e15a-4daf-8d41-615e560d162a"),
                            IconKey = "mdi-dice-5"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("2de31533-bb20-4901-9de9-6460c6b09b01"),
                            IconKey = "mdi-beach"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("1c53a906-2005-42eb-8182-680f51d9af27"),
                            IconKey = "mdi-bus-articulated-front"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("f506239c-78c8-49e3-bb4f-71e4e262be04"),
                            IconKey = "mdi-smoking"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("bcc79ab5-1ba4-490b-8f7e-74b7917426d0"),
                            IconKey = "mdi-fridge"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("31c0bbc0-fa68-4b64-b12e-cb925f6a0f78"),
                            IconKey = "mdi-babe-face"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("315369b7-9184-40d1-8569-58723f2d706b"),
                            IconKey = "mdi-paw"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("08ce6103-f529-4379-a863-89d3c9ef9b63"),
                            IconKey = "mdi-bandage"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("15a5771f-a5ff-4085-9377-60c1413cff43"),
                            IconKey = "mdi-human"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("0cffcd30-855a-4851-8ef9-420c3a0e8612"),
                            IconKey = "mdi-sofa"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("6945dcc7-b5bd-4108-a9f8-18535031ce80"),
                            IconKey = "mdi-memory"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9471a661-26db-44ed-a462-fc2243ff1b6a"),
                            IconKey = "mdi-cellphone-android"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("2f043abc-3c97-4b00-80d7-bdc3df49f359"),
                            IconKey = "mdi-speaker"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("665e3fec-560d-45b3-9548-e9273334dbf8"),
                            IconKey = "mdi-sim"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("ccdd7d3e-b653-4ca0-8cd4-53b58cd02e66"),
                            IconKey = "mdi-silverware-fork-knife"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("521252a7-443c-4d4f-8f54-2796d8cbd977"),
                            IconKey = "mdi-food"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("caba0179-894e-4aa4-bd54-8793687915b8"),
                            IconKey = "mdi-gas-station"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b2c5f1bb-92b7-4129-ae8f-e7db4bede237"),
                            IconKey = "mdi-hospital-building"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("8ea3c5a6-322e-4d72-a735-444fe60e767d"),
                            IconKey = "mdi-shopping"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("952917af-58ca-4497-b062-7d4ffb1f7002"),
                            IconKey = "mdi-glass-cocktail"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("cf037724-be64-454d-9d81-48fd7e24936a"),
                            IconKey = "mdi-filmstrip"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("389f16cc-7196-4eb0-aadc-4fa5d5f5a849"),
                            IconKey = "mdi-bike"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("2c2796b3-8a8c-482d-b6a9-42ac5a23ba9a"),
                            IconKey = "mdi-motorbike"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9e60c8bf-d952-4f62-80f9-2c03a6e6c194"),
                            IconKey = "mdi-wallet-gift-card"
                        });
                });

            modelBuilder.Entity("raBudget.Domain.Entities.SubTransaction", b =>
                {
                    b.Property<Guid>("SubTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("char(36)");

                    b.HasKey("SubTransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SubTransaction");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("raBudget.Domain.Models.Currency", b =>
                {
                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EnglishName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NativeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CurrencyCode");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyCode = 8,
                            Code = "ALL",
                            EnglishName = "Albanian Lek",
                            NativeName = "Leku shqiptar",
                            Symbol = "Lekë"
                        },
                        new
                        {
                            CurrencyCode = 12,
                            Code = "DZD",
                            EnglishName = "Algerian Dinar",
                            NativeName = "دينار جزائري",
                            Symbol = "د.ج.‏"
                        },
                        new
                        {
                            CurrencyCode = 32,
                            Code = "ARS",
                            EnglishName = "Argentine Peso",
                            NativeName = "peso argentino",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 36,
                            Code = "AUD",
                            EnglishName = "Australian Dollar",
                            NativeName = "Australian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 48,
                            Code = "BHD",
                            EnglishName = "Bahraini Dinar",
                            NativeName = "دينار بحريني",
                            Symbol = "د.ب.‏"
                        },
                        new
                        {
                            CurrencyCode = 50,
                            Code = "BDT",
                            EnglishName = "Bangladeshi Taka",
                            NativeName = "বাংলাদেশী টাকা",
                            Symbol = "৳"
                        },
                        new
                        {
                            CurrencyCode = 51,
                            Code = "AMD",
                            EnglishName = "Armenian Dram",
                            NativeName = "հայկական դրամ",
                            Symbol = "֏"
                        },
                        new
                        {
                            CurrencyCode = 68,
                            Code = "BOB",
                            EnglishName = "Bolivian Boliviano",
                            NativeName = "boliviano",
                            Symbol = "Bs"
                        },
                        new
                        {
                            CurrencyCode = 84,
                            Code = "BZD",
                            EnglishName = "Belize Dollar",
                            NativeName = "Belize Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 96,
                            Code = "BND",
                            EnglishName = "Brunei Dollar",
                            NativeName = "Dolar Brunei",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 116,
                            Code = "KHR",
                            EnglishName = "Cambodian Riel",
                            NativeName = "រៀល​កម្ពុជា",
                            Symbol = "៛"
                        },
                        new
                        {
                            CurrencyCode = 124,
                            Code = "CAD",
                            EnglishName = "Canadian Dollar",
                            NativeName = "Canadian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 144,
                            Code = "LKR",
                            EnglishName = "Sri Lankan Rupee",
                            NativeName = "ශ්‍රී ලංකා රුපියල",
                            Symbol = "රු."
                        },
                        new
                        {
                            CurrencyCode = 152,
                            Code = "CLP",
                            EnglishName = "Chilean Peso",
                            NativeName = "CLP",
                            Symbol = "CLP"
                        },
                        new
                        {
                            CurrencyCode = 156,
                            Code = "CNY",
                            EnglishName = "Chinese Yuan",
                            NativeName = "ཡུ་ཨན་",
                            Symbol = "¥"
                        },
                        new
                        {
                            CurrencyCode = 170,
                            Code = "COP",
                            EnglishName = "Colombian Peso",
                            NativeName = "peso colombiano",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 188,
                            Code = "CRC",
                            EnglishName = "Costa Rican Colón",
                            NativeName = "colón costarricense",
                            Symbol = "₡"
                        },
                        new
                        {
                            CurrencyCode = 191,
                            Code = "HRK",
                            EnglishName = "Croatian Kuna",
                            NativeName = "hrvatska kuna",
                            Symbol = "HRK"
                        },
                        new
                        {
                            CurrencyCode = 203,
                            Code = "CZK",
                            EnglishName = "Czech Koruna",
                            NativeName = "česká koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            CurrencyCode = 208,
                            Code = "DKK",
                            EnglishName = "Danish Krone",
                            NativeName = "dansk krone",
                            Symbol = "kr."
                        },
                        new
                        {
                            CurrencyCode = 214,
                            Code = "DOP",
                            EnglishName = "Dominican Peso",
                            NativeName = "peso dominicano",
                            Symbol = "RD$"
                        },
                        new
                        {
                            CurrencyCode = 230,
                            Code = "ETB",
                            EnglishName = "Ethiopian Birr",
                            NativeName = "ETB",
                            Symbol = "Br"
                        },
                        new
                        {
                            CurrencyCode = 320,
                            Code = "GTQ",
                            EnglishName = "Guatemalan Quetzal",
                            NativeName = "quetzal",
                            Symbol = "Q"
                        },
                        new
                        {
                            CurrencyCode = 340,
                            Code = "HNL",
                            EnglishName = "Honduran Lempira",
                            NativeName = "lempira hondureño",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = 344,
                            Code = "HKD",
                            EnglishName = "Hong Kong Dollar",
                            NativeName = "Hong Kong Dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            CurrencyCode = 348,
                            Code = "HUF",
                            EnglishName = "Hungarian Forint",
                            NativeName = "magyar forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            CurrencyCode = 352,
                            Code = "ISK",
                            EnglishName = "Icelandic Króna",
                            NativeName = "íslensk króna",
                            Symbol = "ISK"
                        },
                        new
                        {
                            CurrencyCode = 356,
                            Code = "INR",
                            EnglishName = "Indian Rupee",
                            NativeName = "ভাৰতীয় ৰুপী",
                            Symbol = "₹"
                        },
                        new
                        {
                            CurrencyCode = 360,
                            Code = "IDR",
                            EnglishName = "Indonesian Rupiah",
                            NativeName = "Rupiah Indonesia",
                            Symbol = "Rp"
                        },
                        new
                        {
                            CurrencyCode = 364,
                            Code = "IRR",
                            EnglishName = "Iranian Rial",
                            NativeName = "ریال ایران",
                            Symbol = "ریال"
                        },
                        new
                        {
                            CurrencyCode = 368,
                            Code = "IQD",
                            EnglishName = "Iraqi Dinar",
                            NativeName = "دينار عراقي",
                            Symbol = "د.ع.‏"
                        },
                        new
                        {
                            CurrencyCode = 376,
                            Code = "ILS",
                            EnglishName = "Israeli New Shekel",
                            NativeName = "שקל חדש",
                            Symbol = "₪"
                        },
                        new
                        {
                            CurrencyCode = 388,
                            Code = "JMD",
                            EnglishName = "Jamaican Dollar",
                            NativeName = "Jamaican Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 392,
                            Code = "JPY",
                            EnglishName = "Japanese Yen",
                            NativeName = "日本円",
                            Symbol = "￥"
                        },
                        new
                        {
                            CurrencyCode = 398,
                            Code = "KZT",
                            EnglishName = "Kazakhstani Tenge",
                            NativeName = "Қазақстан теңгесі",
                            Symbol = "₸"
                        },
                        new
                        {
                            CurrencyCode = 400,
                            Code = "JOD",
                            EnglishName = "Jordanian Dinar",
                            NativeName = "دينار أردني",
                            Symbol = "د.أ.‏"
                        },
                        new
                        {
                            CurrencyCode = 404,
                            Code = "KES",
                            EnglishName = "Kenyan Shilling",
                            NativeName = "Shilingi ya Kenya",
                            Symbol = "Ksh"
                        },
                        new
                        {
                            CurrencyCode = 410,
                            Code = "KRW",
                            EnglishName = "South Korean Won",
                            NativeName = "대한민국 원",
                            Symbol = "₩"
                        },
                        new
                        {
                            CurrencyCode = 414,
                            Code = "KWD",
                            EnglishName = "Kuwaiti Dinar",
                            NativeName = "دينار كويتي",
                            Symbol = "د.ك.‏"
                        },
                        new
                        {
                            CurrencyCode = 417,
                            Code = "KGS",
                            EnglishName = "Kyrgystani Som",
                            NativeName = "Кыргызстан сому",
                            Symbol = "сом"
                        },
                        new
                        {
                            CurrencyCode = 418,
                            Code = "LAK",
                            EnglishName = "Laotian Kip",
                            NativeName = "ລາວ ກີບ",
                            Symbol = "₭"
                        },
                        new
                        {
                            CurrencyCode = 422,
                            Code = "LBP",
                            EnglishName = "Lebanese Pound",
                            NativeName = "جنيه لبناني",
                            Symbol = "ل.ل.‏"
                        },
                        new
                        {
                            CurrencyCode = 434,
                            Code = "LYD",
                            EnglishName = "Libyan Dinar",
                            NativeName = "دينار ليبي",
                            Symbol = "د.ل.‏"
                        },
                        new
                        {
                            CurrencyCode = 446,
                            Code = "MOP",
                            EnglishName = "Macanese Pataca",
                            NativeName = "澳門元",
                            Symbol = "MOP$"
                        },
                        new
                        {
                            CurrencyCode = 458,
                            Code = "MYR",
                            EnglishName = "Malaysian Ringgit",
                            NativeName = "Malaysian Ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            CurrencyCode = 462,
                            Code = "MVR",
                            EnglishName = "Maldivian Rufiyaa",
                            NativeName = "MVR",
                            Symbol = "ރ."
                        },
                        new
                        {
                            CurrencyCode = 484,
                            Code = "MXN",
                            EnglishName = "Mexican Peso",
                            NativeName = "peso mexicano",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 496,
                            Code = "MNT",
                            EnglishName = "Mongolian Tugrik",
                            NativeName = "төгрөг",
                            Symbol = "₮"
                        },
                        new
                        {
                            CurrencyCode = 504,
                            Code = "MAD",
                            EnglishName = "Moroccan Dirham",
                            NativeName = "درهم مغربي",
                            Symbol = "د.م.‏"
                        },
                        new
                        {
                            CurrencyCode = 512,
                            Code = "OMR",
                            EnglishName = "Omani Rial",
                            NativeName = "ريال عماني",
                            Symbol = "ر.ع.‏"
                        },
                        new
                        {
                            CurrencyCode = 524,
                            Code = "NPR",
                            EnglishName = "Nepalese Rupee",
                            NativeName = "नेपाली रूपैयाँ",
                            Symbol = "नेरू"
                        },
                        new
                        {
                            CurrencyCode = 554,
                            Code = "NZD",
                            EnglishName = "New Zealand Dollar",
                            NativeName = "New Zealand Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 558,
                            Code = "NIO",
                            EnglishName = "Nicaraguan Córdoba",
                            NativeName = "córdoba nicaragüense",
                            Symbol = "C$"
                        },
                        new
                        {
                            CurrencyCode = 578,
                            Code = "NOK",
                            EnglishName = "Norwegian Krone",
                            NativeName = "norske kroner",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = 586,
                            Code = "PKR",
                            EnglishName = "Pakistani Rupee",
                            NativeName = "روپئیہ",
                            Symbol = "ر"
                        },
                        new
                        {
                            CurrencyCode = 590,
                            Code = "PAB",
                            EnglishName = "Panamanian Balboa",
                            NativeName = "balboa panameño",
                            Symbol = "B/."
                        },
                        new
                        {
                            CurrencyCode = 600,
                            Code = "PYG",
                            EnglishName = "Paraguayan Guarani",
                            NativeName = "guaraní paraguayo",
                            Symbol = "Gs."
                        },
                        new
                        {
                            CurrencyCode = 604,
                            Code = "PEN",
                            EnglishName = "Peruvian Sol",
                            NativeName = "sol peruano",
                            Symbol = "S/"
                        },
                        new
                        {
                            CurrencyCode = 608,
                            Code = "PHP",
                            EnglishName = "Philippine Piso",
                            NativeName = "Philippine Piso",
                            Symbol = "₱"
                        },
                        new
                        {
                            CurrencyCode = 634,
                            Code = "QAR",
                            EnglishName = "Qatari Rial",
                            NativeName = "ريال قطري",
                            Symbol = "ر.ق.‏"
                        },
                        new
                        {
                            CurrencyCode = 643,
                            Code = "RUB",
                            EnglishName = "Russian Ruble",
                            NativeName = "RUB",
                            Symbol = "RUB"
                        },
                        new
                        {
                            CurrencyCode = 646,
                            Code = "RWF",
                            EnglishName = "Rwandan Franc",
                            NativeName = "RWF",
                            Symbol = "RF"
                        },
                        new
                        {
                            CurrencyCode = 682,
                            Code = "SAR",
                            EnglishName = "Saudi Riyal",
                            NativeName = "ريال سعودي",
                            Symbol = "ر.س.‏"
                        },
                        new
                        {
                            CurrencyCode = 702,
                            Code = "SGD",
                            EnglishName = "Singapore Dollar",
                            NativeName = "Singapore Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 704,
                            Code = "VND",
                            EnglishName = "Vietnamese Dong",
                            NativeName = "Đồng Việt Nam",
                            Symbol = "₫"
                        },
                        new
                        {
                            CurrencyCode = 710,
                            Code = "ZAR",
                            EnglishName = "South African Rand",
                            NativeName = "Suid-Afrikaanse rand",
                            Symbol = "R"
                        },
                        new
                        {
                            CurrencyCode = 752,
                            Code = "SEK",
                            EnglishName = "Swedish Krona",
                            NativeName = "ruoŧŧa kruvdno",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = 756,
                            Code = "CHF",
                            EnglishName = "Swiss Franc",
                            NativeName = "Schweizer Franken",
                            Symbol = "CHF"
                        },
                        new
                        {
                            CurrencyCode = 760,
                            Code = "SYP",
                            EnglishName = "Syrian Pound",
                            NativeName = "ليرة سورية",
                            Symbol = "ل.س.‏"
                        },
                        new
                        {
                            CurrencyCode = 764,
                            Code = "THB",
                            EnglishName = "Thai Baht",
                            NativeName = "บาท",
                            Symbol = "฿"
                        },
                        new
                        {
                            CurrencyCode = 780,
                            Code = "TTD",
                            EnglishName = "Trinidad & Tobago Dollar",
                            NativeName = "Trinidad & Tobago Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 784,
                            Code = "AED",
                            EnglishName = "United Arab Emirates Dirham",
                            NativeName = "درهم إماراتي",
                            Symbol = "د.إ.‏"
                        },
                        new
                        {
                            CurrencyCode = 788,
                            Code = "TND",
                            EnglishName = "Tunisian Dinar",
                            NativeName = "دينار تونسي",
                            Symbol = "د.ت.‏"
                        },
                        new
                        {
                            CurrencyCode = 807,
                            Code = "MKD",
                            EnglishName = "Macedonian Denar",
                            NativeName = "Македонски денар",
                            Symbol = "ден"
                        },
                        new
                        {
                            CurrencyCode = 818,
                            Code = "EGP",
                            EnglishName = "Egyptian Pound",
                            NativeName = "جنيه مصري",
                            Symbol = "ج.م.‏"
                        },
                        new
                        {
                            CurrencyCode = 826,
                            Code = "GBP",
                            EnglishName = "British Pound",
                            NativeName = "Punt Prydain",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = 840,
                            Code = "USD",
                            EnglishName = "US Dollar",
                            NativeName = "US ᎠᏕᎳ",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 858,
                            Code = "UYU",
                            EnglishName = "Uruguayan Peso",
                            NativeName = "peso uruguayo",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 860,
                            Code = "UZS",
                            EnglishName = "Uzbekistani Som",
                            NativeName = "Ўзбекистон сўм",
                            Symbol = "сўм"
                        },
                        new
                        {
                            CurrencyCode = 886,
                            Code = "YER",
                            EnglishName = "Yemeni Rial",
                            NativeName = "ريال يمني",
                            Symbol = "ر.ي.‏"
                        },
                        new
                        {
                            CurrencyCode = 901,
                            Code = "TWD",
                            EnglishName = "New Taiwan Dollar",
                            NativeName = "新台幣",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 941,
                            Code = "RSD",
                            EnglishName = "Serbian Dinar",
                            NativeName = "Српски динар",
                            Symbol = "RSD"
                        },
                        new
                        {
                            CurrencyCode = 944,
                            Code = "AZN",
                            EnglishName = "Azerbaijani Manat",
                            NativeName = "AZN",
                            Symbol = "₼"
                        },
                        new
                        {
                            CurrencyCode = 946,
                            Code = "RON",
                            EnglishName = "Romanian Leu",
                            NativeName = "leu românesc",
                            Symbol = "RON"
                        },
                        new
                        {
                            CurrencyCode = 949,
                            Code = "TRY",
                            EnglishName = "Turkish Lira",
                            NativeName = "Türk Lirası",
                            Symbol = "₺"
                        },
                        new
                        {
                            CurrencyCode = 952,
                            Code = "XOF",
                            EnglishName = "West African CFA Franc",
                            NativeName = "Mbuuɗu Seefaa BCEAO",
                            Symbol = "CFA"
                        },
                        new
                        {
                            CurrencyCode = 971,
                            Code = "AFN",
                            EnglishName = "Afghan Afghani",
                            NativeName = "افغانی افغانستان",
                            Symbol = "؋"
                        },
                        new
                        {
                            CurrencyCode = 972,
                            Code = "TJS",
                            EnglishName = "Tajikistani Somoni",
                            NativeName = "Сомонӣ",
                            Symbol = "сом."
                        },
                        new
                        {
                            CurrencyCode = 975,
                            Code = "BGN",
                            EnglishName = "Bulgarian Lev",
                            NativeName = "Български лев",
                            Symbol = "лв."
                        },
                        new
                        {
                            CurrencyCode = 977,
                            Code = "BAM",
                            EnglishName = "Bosnia-Herzegovina Convertible Mark",
                            NativeName = "Конвертибилна марка",
                            Symbol = "КМ"
                        },
                        new
                        {
                            CurrencyCode = 978,
                            Code = "EUR",
                            EnglishName = "Euro",
                            NativeName = "euro",
                            Symbol = "€"
                        },
                        new
                        {
                            CurrencyCode = 980,
                            Code = "UAH",
                            EnglishName = "Ukrainian Hryvnia",
                            NativeName = "українська гривня",
                            Symbol = "₴"
                        },
                        new
                        {
                            CurrencyCode = 981,
                            Code = "GEL",
                            EnglishName = "Georgian Lari",
                            NativeName = "ქართული ლარი",
                            Symbol = "₾"
                        },
                        new
                        {
                            CurrencyCode = 985,
                            Code = "PLN",
                            EnglishName = "Polish Zloty",
                            NativeName = "złoty polski",
                            Symbol = "zł"
                        },
                        new
                        {
                            CurrencyCode = 986,
                            Code = "BRL",
                            EnglishName = "Brazilian Real",
                            NativeName = "Real brasileiro",
                            Symbol = "R$"
                        });
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.HasOne("raBudget.Domain.Models.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.Budget", null)
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory+BudgetedAmount", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.BudgetCategory", null)
                        .WithMany("BudgetedAmounts")
                        .HasForeignKey("BudgetCategoryId");

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BudgetedAmountId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetedAmountId");

                            b1.ToTable("BudgetedAmount");

                            b1.WithOwner()
                                .HasForeignKey("BudgetedAmountId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.SubTransaction", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.Transaction", null)
                        .WithMany("SubTransactions")
                        .HasForeignKey("TransactionId");

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("SubTransactionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("SubTransactionId");

                            b1.ToTable("SubTransaction");

                            b1.WithOwner()
                                .HasForeignKey("SubTransactionId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.Navigation("BudgetCategories");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("BudgetedAmounts");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("SubTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
