// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using raBudget.Infrastructure.Database;

namespace raBudget.Api.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("raBudget.Domain.Entities.Allocation", b =>
                {
                    b.Property<Guid>("AllocationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SourceBudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TargetBudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("AllocationId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetId");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetBalance", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetId");

                    b.ToTable("BudgetBalances");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryIconId")
                        .HasColumnType("char(36)");

                    b.Property<int>("BudgetCategoryType")
                        .HasColumnType("int");

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("BudgetCategoryId");

                    b.HasIndex("BudgetCategoryIconId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory+BudgetedAmount", b =>
                {
                    b.Property<Guid>("BudgetedAmountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BudgetedAmountId");

                    b.HasIndex("BudgetCategoryId");

                    b.ToTable("BudgetedAmount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategoryBalance", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Year", "Month", "BudgetCategoryId");

                    b.ToTable("BudgetCategoryBalances");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategoryIcon", b =>
                {
                    b.Property<Guid>("BudgetCategoryIconId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IconKey")
                        .HasColumnType("longtext");

                    b.HasKey("BudgetCategoryIconId");

                    b.ToTable("BudgetCategoryIcons");

                    b.HasData(
                        new
                        {
                            BudgetCategoryIconId = new Guid("5e8d6d95-9b5d-41fc-9d5e-6bd7c67cbbdf"),
                            IconKey = "mdi-car"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("ade5d9d2-62a3-460d-8221-6a512e1dae3a"),
                            IconKey = "mdi-cart"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b8b1701d-567c-4072-86af-691143cfdf58"),
                            IconKey = "mdi-train-car"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("adcac3e4-2431-47f0-92b5-43cc28477a55"),
                            IconKey = "mdi-wallet-travel"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("971552c6-c014-4c70-8e2e-7348a7816b3a"),
                            IconKey = "mdi-wrench"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("fe0b4e20-d784-4d9c-b674-be1f18b11337"),
                            IconKey = "mdi-basket"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("3c29fe93-4057-41f4-87b9-ae3aad1d7ac7"),
                            IconKey = "mdi-gamepad"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("4cdd7d26-2a55-41da-8619-7d43cde3f98b"),
                            IconKey = "mdi-phone"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("050a5651-ecba-42d6-bec9-ec4bce99878e"),
                            IconKey = "mdi-airplane"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("2dbe3259-dd7f-4932-b268-152d2ce628aa"),
                            IconKey = "mdi-currency-usd-circle-outline"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("a81dcc76-8466-4321-bf26-45e01eb4fa25"),
                            IconKey = "mdi-format-paint"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("05ded520-c1a0-43be-8c5c-46f2105127ce"),
                            IconKey = "mdi-gamepad-square"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("3126c9b1-c645-4236-b1fb-6a903af4a425"),
                            IconKey = "mdi-laptop"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("abfcd591-bb46-4140-8df7-78b918bf5d54"),
                            IconKey = "mdi-camera"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("33297c9c-9e7c-430a-b26c-156db92ebacb"),
                            IconKey = "mdi-city"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("d7eefaa0-7a28-44bd-a2b8-9acc285f1d67"),
                            IconKey = "mdi-fire"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("63708afd-2981-443a-bf42-20abd0ca7569"),
                            IconKey = "mdi-dumbbell"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("33abc471-0ebf-4010-b5ae-616d69a27843"),
                            IconKey = "mdi-coffee"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("142e320c-9443-42bb-bb90-94424e4892da"),
                            IconKey = "mdi-dice-5"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("d48ad1c7-ab9b-40e0-a9cf-8e75cebdce4a"),
                            IconKey = "mdi-beach"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("5afab896-c136-4038-b877-5689f0b737d0"),
                            IconKey = "mdi-bus-articulated-front"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9017e6df-31ad-4f26-9823-c18649fb0050"),
                            IconKey = "mdi-smoking"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("d6becd4b-5787-4e5a-84ba-aa7d4fba4dba"),
                            IconKey = "mdi-fridge"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9babdfb1-2a4c-4dfd-8ab3-156318b8dfa9"),
                            IconKey = "mdi-baby-face"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("2ebcf1a1-b189-4810-a752-5135834de4b0"),
                            IconKey = "mdi-paw"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("04d78c03-4815-43d3-85bc-0be77feb7830"),
                            IconKey = "mdi-bandage"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("78a22cc1-ff4f-4451-bef2-4b1d7a22f92d"),
                            IconKey = "mdi-human"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("d761ff55-56cc-4bbb-941f-df3e337ab340"),
                            IconKey = "mdi-sofa"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("35e4a316-757c-4eac-8106-42e44ce6f202"),
                            IconKey = "mdi-memory"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("3a970a19-2543-4079-9e1b-e2bd9d8ca9b3"),
                            IconKey = "mdi-cellphone-android"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("9ac070b6-760f-4fdd-9395-b36b07e46096"),
                            IconKey = "mdi-speaker"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b4f0048f-0577-416c-8489-f31ec24cdf9d"),
                            IconKey = "mdi-sim"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("21d70b28-1532-44a0-985f-d2c97d4db1cf"),
                            IconKey = "mdi-silverware-fork-knife"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("2f473088-bbfe-44de-8dc2-d264e105e9e0"),
                            IconKey = "mdi-food"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("fea7aef0-854c-42f5-84d0-c92fd4a6fc84"),
                            IconKey = "mdi-gas-station"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("05cb0931-6023-49be-8112-67cf19f43217"),
                            IconKey = "mdi-hospital-building"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("61aba482-a483-452a-adfa-fabccae6d29c"),
                            IconKey = "mdi-shopping"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("0098fb49-45b6-4f54-b7f2-df5c0654723e"),
                            IconKey = "mdi-glass-cocktail"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("0b12e5fe-367d-4f5f-b7ea-1175c14c5fcd"),
                            IconKey = "mdi-filmstrip"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b005e998-0c0b-4ddc-bd73-166a67e8659b"),
                            IconKey = "mdi-bike"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("2b9e95b8-1b25-4ef7-a1bb-dab9e2607b91"),
                            IconKey = "mdi-motorbike"
                        },
                        new
                        {
                            BudgetCategoryIconId = new Guid("b9414560-67f9-41fb-ba6d-61b929ccd125"),
                            IconKey = "mdi-wallet-giftcard"
                        });
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("EnglishName")
                        .HasColumnType("longtext");

                    b.Property<string>("NativeName")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.HasKey("CurrencyCode");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencyCode = 8,
                            Code = "ALL",
                            EnglishName = "Albanian Lek",
                            NativeName = "Leku shqiptar",
                            Symbol = "Lekë"
                        },
                        new
                        {
                            CurrencyCode = 12,
                            Code = "DZD",
                            EnglishName = "Algerian Dinar",
                            NativeName = "دينار جزائري",
                            Symbol = "د.ج.‏"
                        },
                        new
                        {
                            CurrencyCode = 32,
                            Code = "ARS",
                            EnglishName = "Argentine Peso",
                            NativeName = "peso argentino",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 36,
                            Code = "AUD",
                            EnglishName = "Australian Dollar",
                            NativeName = "Australian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 48,
                            Code = "BHD",
                            EnglishName = "Bahraini Dinar",
                            NativeName = "دينار بحريني",
                            Symbol = "د.ب.‏"
                        },
                        new
                        {
                            CurrencyCode = 50,
                            Code = "BDT",
                            EnglishName = "Bangladeshi Taka",
                            NativeName = "বাংলাদেশী টাকা",
                            Symbol = "৳"
                        },
                        new
                        {
                            CurrencyCode = 51,
                            Code = "AMD",
                            EnglishName = "Armenian Dram",
                            NativeName = "հայկական դրամ",
                            Symbol = "֏"
                        },
                        new
                        {
                            CurrencyCode = 68,
                            Code = "BOB",
                            EnglishName = "Bolivian Boliviano",
                            NativeName = "boliviano",
                            Symbol = "Bs"
                        },
                        new
                        {
                            CurrencyCode = 84,
                            Code = "BZD",
                            EnglishName = "Belize Dollar",
                            NativeName = "Belize Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 96,
                            Code = "BND",
                            EnglishName = "Brunei Dollar",
                            NativeName = "Dolar Brunei",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 116,
                            Code = "KHR",
                            EnglishName = "Cambodian Riel",
                            NativeName = "រៀល​កម្ពុជា",
                            Symbol = "៛"
                        },
                        new
                        {
                            CurrencyCode = 124,
                            Code = "CAD",
                            EnglishName = "Canadian Dollar",
                            NativeName = "Canadian Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 144,
                            Code = "LKR",
                            EnglishName = "Sri Lankan Rupee",
                            NativeName = "ශ්‍රී ලංකා රුපියල",
                            Symbol = "රු."
                        },
                        new
                        {
                            CurrencyCode = 152,
                            Code = "CLP",
                            EnglishName = "Chilean Peso",
                            NativeName = "CLP",
                            Symbol = "CLP"
                        },
                        new
                        {
                            CurrencyCode = 156,
                            Code = "CNY",
                            EnglishName = "Chinese Yuan",
                            NativeName = "ཡུ་ཨན་",
                            Symbol = "¥"
                        },
                        new
                        {
                            CurrencyCode = 170,
                            Code = "COP",
                            EnglishName = "Colombian Peso",
                            NativeName = "peso colombiano",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 188,
                            Code = "CRC",
                            EnglishName = "Costa Rican Colón",
                            NativeName = "colón costarricense",
                            Symbol = "₡"
                        },
                        new
                        {
                            CurrencyCode = 191,
                            Code = "HRK",
                            EnglishName = "Croatian Kuna",
                            NativeName = "hrvatska kuna",
                            Symbol = "HRK"
                        },
                        new
                        {
                            CurrencyCode = 203,
                            Code = "CZK",
                            EnglishName = "Czech Koruna",
                            NativeName = "česká koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            CurrencyCode = 208,
                            Code = "DKK",
                            EnglishName = "Danish Krone",
                            NativeName = "dansk krone",
                            Symbol = "kr."
                        },
                        new
                        {
                            CurrencyCode = 214,
                            Code = "DOP",
                            EnglishName = "Dominican Peso",
                            NativeName = "peso dominicano",
                            Symbol = "RD$"
                        },
                        new
                        {
                            CurrencyCode = 230,
                            Code = "ETB",
                            EnglishName = "Ethiopian Birr",
                            NativeName = "ETB",
                            Symbol = "Br"
                        },
                        new
                        {
                            CurrencyCode = 320,
                            Code = "GTQ",
                            EnglishName = "Guatemalan Quetzal",
                            NativeName = "quetzal",
                            Symbol = "Q"
                        },
                        new
                        {
                            CurrencyCode = 340,
                            Code = "HNL",
                            EnglishName = "Honduran Lempira",
                            NativeName = "lempira hondureño",
                            Symbol = "L"
                        },
                        new
                        {
                            CurrencyCode = 344,
                            Code = "HKD",
                            EnglishName = "Hong Kong Dollar",
                            NativeName = "Hong Kong Dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            CurrencyCode = 348,
                            Code = "HUF",
                            EnglishName = "Hungarian Forint",
                            NativeName = "magyar forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            CurrencyCode = 352,
                            Code = "ISK",
                            EnglishName = "Icelandic Króna",
                            NativeName = "íslensk króna",
                            Symbol = "ISK"
                        },
                        new
                        {
                            CurrencyCode = 356,
                            Code = "INR",
                            EnglishName = "Indian Rupee",
                            NativeName = "ভাৰতীয় ৰুপী",
                            Symbol = "₹"
                        },
                        new
                        {
                            CurrencyCode = 360,
                            Code = "IDR",
                            EnglishName = "Indonesian Rupiah",
                            NativeName = "Rupiah Indonesia",
                            Symbol = "Rp"
                        },
                        new
                        {
                            CurrencyCode = 364,
                            Code = "IRR",
                            EnglishName = "Iranian Rial",
                            NativeName = "ریال ایران",
                            Symbol = "ریال"
                        },
                        new
                        {
                            CurrencyCode = 368,
                            Code = "IQD",
                            EnglishName = "Iraqi Dinar",
                            NativeName = "دينار عراقي",
                            Symbol = "د.ع.‏"
                        },
                        new
                        {
                            CurrencyCode = 376,
                            Code = "ILS",
                            EnglishName = "Israeli New Shekel",
                            NativeName = "שקל חדש",
                            Symbol = "₪"
                        },
                        new
                        {
                            CurrencyCode = 388,
                            Code = "JMD",
                            EnglishName = "Jamaican Dollar",
                            NativeName = "Jamaican Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 392,
                            Code = "JPY",
                            EnglishName = "Japanese Yen",
                            NativeName = "日本円",
                            Symbol = "￥"
                        },
                        new
                        {
                            CurrencyCode = 398,
                            Code = "KZT",
                            EnglishName = "Kazakhstani Tenge",
                            NativeName = "Қазақстан теңгесі",
                            Symbol = "₸"
                        },
                        new
                        {
                            CurrencyCode = 400,
                            Code = "JOD",
                            EnglishName = "Jordanian Dinar",
                            NativeName = "دينار أردني",
                            Symbol = "د.أ.‏"
                        },
                        new
                        {
                            CurrencyCode = 404,
                            Code = "KES",
                            EnglishName = "Kenyan Shilling",
                            NativeName = "Shilingi ya Kenya",
                            Symbol = "Ksh"
                        },
                        new
                        {
                            CurrencyCode = 410,
                            Code = "KRW",
                            EnglishName = "South Korean Won",
                            NativeName = "대한민국 원",
                            Symbol = "₩"
                        },
                        new
                        {
                            CurrencyCode = 414,
                            Code = "KWD",
                            EnglishName = "Kuwaiti Dinar",
                            NativeName = "دينار كويتي",
                            Symbol = "د.ك.‏"
                        },
                        new
                        {
                            CurrencyCode = 417,
                            Code = "KGS",
                            EnglishName = "Kyrgystani Som",
                            NativeName = "Кыргызстан сому",
                            Symbol = "сом"
                        },
                        new
                        {
                            CurrencyCode = 418,
                            Code = "LAK",
                            EnglishName = "Laotian Kip",
                            NativeName = "ລາວ ກີບ",
                            Symbol = "₭"
                        },
                        new
                        {
                            CurrencyCode = 422,
                            Code = "LBP",
                            EnglishName = "Lebanese Pound",
                            NativeName = "جنيه لبناني",
                            Symbol = "ل.ل.‏"
                        },
                        new
                        {
                            CurrencyCode = 434,
                            Code = "LYD",
                            EnglishName = "Libyan Dinar",
                            NativeName = "دينار ليبي",
                            Symbol = "د.ل.‏"
                        },
                        new
                        {
                            CurrencyCode = 446,
                            Code = "MOP",
                            EnglishName = "Macanese Pataca",
                            NativeName = "澳門元",
                            Symbol = "MOP$"
                        },
                        new
                        {
                            CurrencyCode = 458,
                            Code = "MYR",
                            EnglishName = "Malaysian Ringgit",
                            NativeName = "Malaysian Ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            CurrencyCode = 462,
                            Code = "MVR",
                            EnglishName = "Maldivian Rufiyaa",
                            NativeName = "MVR",
                            Symbol = "ރ."
                        },
                        new
                        {
                            CurrencyCode = 484,
                            Code = "MXN",
                            EnglishName = "Mexican Peso",
                            NativeName = "peso mexicano",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 496,
                            Code = "MNT",
                            EnglishName = "Mongolian Tugrik",
                            NativeName = "төгрөг",
                            Symbol = "₮"
                        },
                        new
                        {
                            CurrencyCode = 504,
                            Code = "MAD",
                            EnglishName = "Moroccan Dirham",
                            NativeName = "درهم مغربي",
                            Symbol = "د.م.‏"
                        },
                        new
                        {
                            CurrencyCode = 512,
                            Code = "OMR",
                            EnglishName = "Omani Rial",
                            NativeName = "ريال عماني",
                            Symbol = "ر.ع.‏"
                        },
                        new
                        {
                            CurrencyCode = 524,
                            Code = "NPR",
                            EnglishName = "Nepalese Rupee",
                            NativeName = "नेपाली रूपैयाँ",
                            Symbol = "नेरू"
                        },
                        new
                        {
                            CurrencyCode = 554,
                            Code = "NZD",
                            EnglishName = "New Zealand Dollar",
                            NativeName = "New Zealand Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 558,
                            Code = "NIO",
                            EnglishName = "Nicaraguan Córdoba",
                            NativeName = "córdoba nicaragüense",
                            Symbol = "C$"
                        },
                        new
                        {
                            CurrencyCode = 578,
                            Code = "NOK",
                            EnglishName = "Norwegian Krone",
                            NativeName = "norske kroner",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = 586,
                            Code = "PKR",
                            EnglishName = "Pakistani Rupee",
                            NativeName = "روپئیہ",
                            Symbol = "ر"
                        },
                        new
                        {
                            CurrencyCode = 590,
                            Code = "PAB",
                            EnglishName = "Panamanian Balboa",
                            NativeName = "balboa panameño",
                            Symbol = "B/."
                        },
                        new
                        {
                            CurrencyCode = 600,
                            Code = "PYG",
                            EnglishName = "Paraguayan Guarani",
                            NativeName = "guaraní paraguayo",
                            Symbol = "Gs."
                        },
                        new
                        {
                            CurrencyCode = 604,
                            Code = "PEN",
                            EnglishName = "Peruvian Sol",
                            NativeName = "sol peruano",
                            Symbol = "S/"
                        },
                        new
                        {
                            CurrencyCode = 608,
                            Code = "PHP",
                            EnglishName = "Philippine Piso",
                            NativeName = "Philippine Piso",
                            Symbol = "₱"
                        },
                        new
                        {
                            CurrencyCode = 634,
                            Code = "QAR",
                            EnglishName = "Qatari Rial",
                            NativeName = "ريال قطري",
                            Symbol = "ر.ق.‏"
                        },
                        new
                        {
                            CurrencyCode = 643,
                            Code = "RUB",
                            EnglishName = "Russian Ruble",
                            NativeName = "RUB",
                            Symbol = "RUB"
                        },
                        new
                        {
                            CurrencyCode = 646,
                            Code = "RWF",
                            EnglishName = "Rwandan Franc",
                            NativeName = "RWF",
                            Symbol = "RF"
                        },
                        new
                        {
                            CurrencyCode = 682,
                            Code = "SAR",
                            EnglishName = "Saudi Riyal",
                            NativeName = "ريال سعودي",
                            Symbol = "ر.س.‏"
                        },
                        new
                        {
                            CurrencyCode = 702,
                            Code = "SGD",
                            EnglishName = "Singapore Dollar",
                            NativeName = "Singapore Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 704,
                            Code = "VND",
                            EnglishName = "Vietnamese Dong",
                            NativeName = "Đồng Việt Nam",
                            Symbol = "₫"
                        },
                        new
                        {
                            CurrencyCode = 710,
                            Code = "ZAR",
                            EnglishName = "South African Rand",
                            NativeName = "Suid-Afrikaanse rand",
                            Symbol = "R"
                        },
                        new
                        {
                            CurrencyCode = 752,
                            Code = "SEK",
                            EnglishName = "Swedish Krona",
                            NativeName = "ruoŧŧa kruvdno",
                            Symbol = "kr"
                        },
                        new
                        {
                            CurrencyCode = 756,
                            Code = "CHF",
                            EnglishName = "Swiss Franc",
                            NativeName = "Schweizer Franken",
                            Symbol = "CHF"
                        },
                        new
                        {
                            CurrencyCode = 760,
                            Code = "SYP",
                            EnglishName = "Syrian Pound",
                            NativeName = "ليرة سورية",
                            Symbol = "ل.س.‏"
                        },
                        new
                        {
                            CurrencyCode = 764,
                            Code = "THB",
                            EnglishName = "Thai Baht",
                            NativeName = "บาท",
                            Symbol = "฿"
                        },
                        new
                        {
                            CurrencyCode = 780,
                            Code = "TTD",
                            EnglishName = "Trinidad & Tobago Dollar",
                            NativeName = "Trinidad & Tobago Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 784,
                            Code = "AED",
                            EnglishName = "United Arab Emirates Dirham",
                            NativeName = "درهم إماراتي",
                            Symbol = "د.إ.‏"
                        },
                        new
                        {
                            CurrencyCode = 788,
                            Code = "TND",
                            EnglishName = "Tunisian Dinar",
                            NativeName = "دينار تونسي",
                            Symbol = "د.ت.‏"
                        },
                        new
                        {
                            CurrencyCode = 807,
                            Code = "MKD",
                            EnglishName = "Macedonian Denar",
                            NativeName = "Македонски денар",
                            Symbol = "ден"
                        },
                        new
                        {
                            CurrencyCode = 818,
                            Code = "EGP",
                            EnglishName = "Egyptian Pound",
                            NativeName = "جنيه مصري",
                            Symbol = "ج.م.‏"
                        },
                        new
                        {
                            CurrencyCode = 826,
                            Code = "GBP",
                            EnglishName = "British Pound",
                            NativeName = "Punt Prydain",
                            Symbol = "£"
                        },
                        new
                        {
                            CurrencyCode = 840,
                            Code = "USD",
                            EnglishName = "US Dollar",
                            NativeName = "US ᎠᏕᎳ",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 858,
                            Code = "UYU",
                            EnglishName = "Uruguayan Peso",
                            NativeName = "peso uruguayo",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 860,
                            Code = "UZS",
                            EnglishName = "Uzbekistani Som",
                            NativeName = "Ўзбекистон сўм",
                            Symbol = "сўм"
                        },
                        new
                        {
                            CurrencyCode = 886,
                            Code = "YER",
                            EnglishName = "Yemeni Rial",
                            NativeName = "ريال يمني",
                            Symbol = "ر.ي.‏"
                        },
                        new
                        {
                            CurrencyCode = 901,
                            Code = "TWD",
                            EnglishName = "New Taiwan Dollar",
                            NativeName = "新台幣",
                            Symbol = "$"
                        },
                        new
                        {
                            CurrencyCode = 941,
                            Code = "RSD",
                            EnglishName = "Serbian Dinar",
                            NativeName = "Српски динар",
                            Symbol = "RSD"
                        },
                        new
                        {
                            CurrencyCode = 944,
                            Code = "AZN",
                            EnglishName = "Azerbaijani Manat",
                            NativeName = "AZN",
                            Symbol = "₼"
                        },
                        new
                        {
                            CurrencyCode = 946,
                            Code = "RON",
                            EnglishName = "Romanian Leu",
                            NativeName = "leu românesc",
                            Symbol = "RON"
                        },
                        new
                        {
                            CurrencyCode = 949,
                            Code = "TRY",
                            EnglishName = "Turkish Lira",
                            NativeName = "Türk Lirası",
                            Symbol = "₺"
                        },
                        new
                        {
                            CurrencyCode = 952,
                            Code = "XOF",
                            EnglishName = "West African CFA Franc",
                            NativeName = "Mbuuɗu Seefaa BCEAO",
                            Symbol = "CFA"
                        },
                        new
                        {
                            CurrencyCode = 971,
                            Code = "AFN",
                            EnglishName = "Afghan Afghani",
                            NativeName = "افغانی افغانستان",
                            Symbol = "؋"
                        },
                        new
                        {
                            CurrencyCode = 972,
                            Code = "TJS",
                            EnglishName = "Tajikistani Somoni",
                            NativeName = "Сомонӣ",
                            Symbol = "сом."
                        },
                        new
                        {
                            CurrencyCode = 975,
                            Code = "BGN",
                            EnglishName = "Bulgarian Lev",
                            NativeName = "Български лев",
                            Symbol = "лв."
                        },
                        new
                        {
                            CurrencyCode = 977,
                            Code = "BAM",
                            EnglishName = "Bosnia-Herzegovina Convertible Mark",
                            NativeName = "Конвертибилна марка",
                            Symbol = "КМ"
                        },
                        new
                        {
                            CurrencyCode = 978,
                            Code = "EUR",
                            EnglishName = "Euro",
                            NativeName = "euro",
                            Symbol = "€"
                        },
                        new
                        {
                            CurrencyCode = 980,
                            Code = "UAH",
                            EnglishName = "Ukrainian Hryvnia",
                            NativeName = "українська гривня",
                            Symbol = "₴"
                        },
                        new
                        {
                            CurrencyCode = 981,
                            Code = "GEL",
                            EnglishName = "Georgian Lari",
                            NativeName = "ქართული ლარი",
                            Symbol = "₾"
                        },
                        new
                        {
                            CurrencyCode = 985,
                            Code = "PLN",
                            EnglishName = "Polish Zloty",
                            NativeName = "złoty polski",
                            Symbol = "zł"
                        },
                        new
                        {
                            CurrencyCode = 986,
                            Code = "BRL",
                            EnglishName = "Brazilian Real",
                            NativeName = "Real brasileiro",
                            Symbol = "R$"
                        });
                });

            modelBuilder.Entity("raBudget.Domain.Entities.SubTransaction", b =>
                {
                    b.Property<Guid>("SubTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("char(36)");

                    b.HasKey("SubTransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SubTransaction");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.TransactionTemplate", b =>
                {
                    b.Property<Guid>("TransactionTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.HasKey("TransactionTemplateId");

                    b.ToTable("TransactionTemplates");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Allocation", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("AllocationId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("AllocationId");

                            b1.ToTable("Allocations");

                            b1.WithOwner()
                                .HasForeignKey("AllocationId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetBalance", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "IncomeTotal", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "SavingTotal", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "SpendingTotal", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "TotalBalance", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "UnassignedFunds", b1 =>
                        {
                            b1.Property<Guid>("BudgetBalanceBudgetId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetBalanceBudgetId");

                            b1.ToTable("BudgetBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetBalanceBudgetId");
                        });

                    b.Navigation("IncomeTotal");

                    b.Navigation("SavingTotal");

                    b.Navigation("SpendingTotal");

                    b.Navigation("TotalBalance");

                    b.Navigation("UnassignedFunds");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.BudgetCategoryIcon", "BudgetCategoryIcon")
                        .WithMany()
                        .HasForeignKey("BudgetCategoryIconId");

                    b.HasOne("raBudget.Domain.Entities.Budget", null)
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId");

                    b.Navigation("BudgetCategoryIcon");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory+BudgetedAmount", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.BudgetCategory", null)
                        .WithMany("BudgetedAmounts")
                        .HasForeignKey("BudgetCategoryId");

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BudgetedAmountId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetedAmountId");

                            b1.ToTable("BudgetedAmount");

                            b1.WithOwner()
                                .HasForeignKey("BudgetedAmountId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategoryBalance", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "AllocationsTotal", b1 =>
                        {
                            b1.Property<int>("BudgetCategoryBalanceYear")
                                .HasColumnType("int");

                            b1.Property<int>("BudgetCategoryBalanceMonth")
                                .HasColumnType("int");

                            b1.Property<Guid>("BudgetCategoryBalanceBudgetCategoryId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetCategoryBalanceYear", "BudgetCategoryBalanceMonth", "BudgetCategoryBalanceBudgetCategoryId");

                            b1.ToTable("BudgetCategoryBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCategoryBalanceYear", "BudgetCategoryBalanceMonth", "BudgetCategoryBalanceBudgetCategoryId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "BudgetedAmount", b1 =>
                        {
                            b1.Property<int>("BudgetCategoryBalanceYear")
                                .HasColumnType("int");

                            b1.Property<int>("BudgetCategoryBalanceMonth")
                                .HasColumnType("int");

                            b1.Property<Guid>("BudgetCategoryBalanceBudgetCategoryId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetCategoryBalanceYear", "BudgetCategoryBalanceMonth", "BudgetCategoryBalanceBudgetCategoryId");

                            b1.ToTable("BudgetCategoryBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCategoryBalanceYear", "BudgetCategoryBalanceMonth", "BudgetCategoryBalanceBudgetCategoryId");
                        });

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "TransactionsTotal", b1 =>
                        {
                            b1.Property<int>("BudgetCategoryBalanceYear")
                                .HasColumnType("int");

                            b1.Property<int>("BudgetCategoryBalanceMonth")
                                .HasColumnType("int");

                            b1.Property<Guid>("BudgetCategoryBalanceBudgetCategoryId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("BudgetCategoryBalanceYear", "BudgetCategoryBalanceMonth", "BudgetCategoryBalanceBudgetCategoryId");

                            b1.ToTable("BudgetCategoryBalances");

                            b1.WithOwner()
                                .HasForeignKey("BudgetCategoryBalanceYear", "BudgetCategoryBalanceMonth", "BudgetCategoryBalanceBudgetCategoryId");
                        });

                    b.Navigation("AllocationsTotal");

                    b.Navigation("BudgetedAmount");

                    b.Navigation("TransactionsTotal");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.SubTransaction", b =>
                {
                    b.HasOne("raBudget.Domain.Entities.Transaction", null)
                        .WithMany("SubTransactions")
                        .HasForeignKey("TransactionId");

                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("SubTransactionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("SubTransactionId");

                            b1.ToTable("SubTransaction");

                            b1.WithOwner()
                                .HasForeignKey("SubTransactionId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.TransactionTemplate", b =>
                {
                    b.OwnsOne("raBudget.Domain.ValueObjects.MoneyAmount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionTemplateId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<int>("CurrencyCode")
                                .HasColumnType("int");

                            b1.HasKey("TransactionTemplateId");

                            b1.ToTable("TransactionTemplates");

                            b1.WithOwner()
                                .HasForeignKey("TransactionTemplateId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Budget", b =>
                {
                    b.Navigation("BudgetCategories");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("BudgetedAmounts");
                });

            modelBuilder.Entity("raBudget.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("SubTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
